name: Publish to NPM

on:
  release:
    types: [published]

permissions:
  contents: write  # Required for uploading release assets
  packages: write  # Required for publishing packages

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Run linter
      run: npm run lint
    
    - name: Publish to NPM
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    - name: Create package tarball
      run: |
        npm pack
        ls -la *.tgz
    
    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: '*.tgz'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}