name: Test & Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Clear npm cache
      run: npm cache clean --force
    
    - name: Delete package-lock.json
      run: rm -f package-lock.json
    
    - name: Install dependencies
      run: npm install
    
    - name: Run linter
      run: npm run lint
    
    - name: Run tests
      run: npm run test:coverage
    
    - name: Upload coverage to Codecov
      if: matrix.node-version == '18.x'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
    
    - name: Test CLI functionality
      run: |
        chmod +x bin/api-documenter
        node bin/api-documenter --help
        echo "Testing scan without AI..."
        mkdir -p examples
        echo 'const express = require("express"); const app = express(); app.get("/test", (req, res) => res.json({}));' > examples/test.js
        node bin/api-documenter scan examples/ --no-ai --output ./test-docs
        ls -la test-docs/ || echo "No test-docs directory created"

  integration-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Clear npm cache
      run: npm cache clean --force
    
    - name: Delete package-lock.json
      run: rm -f package-lock.json
    
    - name: Install dependencies
      run: npm install
    
    - name: Create test files
      run: |
        mkdir -p examples
        echo 'const express = require("express"); const app = express(); app.get("/users", (req, res) => res.json([])); app.post("/users", (req, res) => res.status(201).json({}));' > examples/users.js
    
    - name: Test with AI (if API key available)
      env:
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: |
        if [ -n "$GROQ_API_KEY" ]; then
          echo "Testing with AI integration..."
          node bin/api-documenter scan examples/ --output ./ai-test-docs
          ls -la ai-test-docs/ || echo "No ai-test-docs directory created"
        else
          echo "Skipping AI tests - no API key available"
          node bin/api-documenter scan examples/ --no-ai --output ./no-ai-test-docs
          ls -la no-ai-test-docs/ || echo "No no-ai-test-docs directory created"
        fi