name: Test & Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
    
    - name: Run tests
      run: npm run test:coverage
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
    
    - name: Test CLI functionality
      run: |
        chmod +x bin/api-documenter
        node bin/api-documenter --help
        echo "Testing scan without AI..."
        node bin/api-documenter scan examples/ --no-ai --output ./test-docs
        ls -la test-docs/

  integration-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Test with AI (if API key available)
      env:
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: |
        if [ -n "$GROQ_API_KEY" ]; then
          echo "Testing with AI integration..."
          node bin/api-documenter scan examples/ --output ./ai-test-docs
          ls -la ai-test-docs/
        else
          echo "Skipping AI tests - no API key available"
        fi